version: "3.8"

services:
  db:
    container_name: database-store
    image: bitnami/postgresql:latest
    ports:
      - '$DB_PORT:$DB_PORT'
    environment:
      POSTGRES_USER: $POSTGRES_USER 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      DBDATA: $DB_DATA
    volumes:
      - ./data:$DB_DATA